set(_CATKIN_CURRENT_PACKAGE "display_laser")
set(display_laser_VERSION "0.0.0")
set(display_laser_MAINTAINER "olivier <olivier@todo.todo>")
set(display_laser_PACKAGE_FORMAT "1")
set(display_laser_BUILD_DEPENDS )
set(display_laser_BUILD_EXPORT_DEPENDS )
set(display_laser_BUILDTOOL_DEPENDS "catkin")
set(display_laser_BUILDTOOL_EXPORT_DEPENDS )
set(display_laser_EXEC_DEPENDS )
set(display_laser_RUN_DEPENDS )
set(display_laser_TEST_DEPENDS )
set(display_laser_DOC_DEPENDS )
set(display_laser_URL_WEBSITE "")
set(display_laser_URL_BUGTRACKER "")
set(display_laser_URL_REPOSITORY "")
set(display_laser_DEPRECATED "")